In [ ]:
import numpy as np
import pandas as pd

import statsmodels
import statsmodels.api as sm
from statsmodels.tsa.stattools import coint, adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns; sns.set(style="whitegrid")

# Load all three days of price data
prices_day_neg2 = pd.read_csv('prices_round_1_day_-2.csv', sep=';')
prices_day_neg1 = pd.read_csv('prices_round_1_day_-1.csv', sep=';')
prices_day_0 = pd.read_csv('prices_round_1_day_0.csv', sep=';')

# Combine into one DataFrame
prices_df = pd.concat([prices_day_neg2, prices_day_neg1, prices_day_0], ignore_index=True)

prices_df.head(10)

In [ ]:
"""

#Tomatoes
tomatoes_prices_1_df = prices_1_df.loc[prices_1_df['product'] == "TOMATOES"]
tomatoes_prices_1_df.head()
"""

$i$ is the order depth:
$$ \text{VWAP}_t = \frac{\sum_i (ASK_i)_t \cdot (BID_i)\_VOL_t + \sum_i(BID_i)_t \cdot (ASK_i)\_VOL_t}{\sum_i ASK_i\_VOL_t + BID_i\_VOL_t} $$

In [6]:
#Emerald
emeralds_prices_1_df = prices_1_df.loc[prices_1_df['product'] == "EMERALDS"]
emeralds_prices_1_df.head()

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
1,-1,0,EMERALDS,9992,14,9990,29,NaN,NaN,10008,14,10010,29,NaN,NaN,10000.0,0.0
2,-1,100,EMERALDS,9992,11,9990,22,NaN,NaN,10008,11,10010,22,NaN,NaN,10000.0,0.0
4,-1,200,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
7,-1,300,EMERALDS,9992,11,9990,29,NaN,NaN,10008,11,10010,29,NaN,NaN,10000.0,0.0
9,-1,400,EMERALDS,9992,12,9990,25,NaN,NaN,10008,12,10010,25,NaN,NaN,10000.0,0.0

In [4]:
prices_2_df = pd.read_csv('prices_round_0_day_-2.csv', sep=';')
prices_2_df.head()

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
0,-2,0,EMERALDS,9992,11,9990,25,NaN,NaN,10008,11,10010,25,NaN,NaN,10000.0,0.0
1,-2,0,TOMATOES,4993,7,4992,17,NaN,NaN,5007,7,5008,17,NaN,NaN,5000.0,0.0
2,-2,100,TOMATOES,4998,5,4993,7,4992.0,16.0,5007,7,5008,16,NaN,NaN,5002.5,0.0
3,-2,100,EMERALDS,9992,15,9990,20,NaN,NaN,10008,15,10010,20,NaN,NaN,10000.0,0.0
4,-2,200,TOMATOES,4994,6,4993,20,NaN,NaN,5008,6,5009,20,NaN,NaN,5001.0,0.0

In [ ]:
IPR_prices_df = prices_df.loc[prices_df['product'] == "INTARIAN_PEPPER_ROOT"].sort_values('global_timestamp')
IPR_prices_df['mid_price'] = IPR_prices_df['mid_price'].replace(0, np.nan).ffill()
IPR_prices_df.head()